### ISSUE TITLE
Avoid ACTIONS_ALLOW_UNSECURE_COMMANDS

### ISSUE THREAD

**Issue by woodie** [nelonoel/branch-name#10]
I'd like to avoid having to set ACTIONS_ALLOW_UNSECURE_COMMANDS.

```yml
  - name: Set branch name unsecure
    uses: nelonoel/branch-name@v1
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

  - name: Set branch name
    run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
```
